Build binaries for each release tag
cosmos/ethermint-archive pull request #105
Opened 2017-05-20 10:31 UTC by nodar-chkuaselidze

- Added `STATIC` variable for Makefile which produces static builds (Default is STATIC=1, so it builds static binary)
- Removed `get_vendor_deps` from Makefile because it slows down builds, if you're building frequently.. So you will just run it once
- `make install` will call `make build` and copy the binary file
- `make build-docker` defaults to STATIC build as well (So you can use it with Alpine)
- `make build-docker` will use `make build`

`make dist` cross-compiles and zips ethermint binaries using https://github.com/karalabe/xgo for building(ethereum has CGO dependency). It compiles non-static binaries. Target list was taken from tendermint.  
When you run `make dist` it will compile current commit, take version information from version/version.go file and create build/pkg folder to store compiled binaries and build/dist zip archives.
Example Folder structure:
```build
├── dist
│   ├── ethermint-0.1.0-SHA256SUMS
│   ├── ethermint-0.1.0-darwin-10.6-386.zip
│   ├── ethermint-0.1.0-darwin-10.6-amd64.zip
│   ├── ethermint-0.1.0-linux-386.zip
│   ├── ethermint-0.1.0-linux-amd64.zip
│   ├── ethermint-0.1.0-linux-arm-5.zip
│   ├── ethermint-0.1.0-windows-4.0-386.exe.zip
│   └── ethermint-0.1.0-windows-4.0-amd64.exe.zip
└── pkg
    ├── ethermint-darwin-10.6-386
    ├── ethermint-darwin-10.6-amd64
    ├── ethermint-linux-386
    ├── ethermint-linux-amd64
    ├── ethermint-linux-arm-5
    ├── ethermint-windows-4.0-386.exe
    └── ethermint-windows-4.0-amd64.exe
```

This pull request closes: #89, #103, #104

2017-05-22 19:20 UTC, adrianbrink requested changes
With the minor change this is good to merge.

2017-05-22 19:20 UTC, adrianbrink commented on Makefile
> +	@cp ./build/ethermint  $(GOPATH)/bin/ethermint
Could we instead use ```@go install ./cmd/ethermint``` so that we guarantee a fresh build.

2017-05-22 19:57 UTC, nodar-chkuaselidze commented on Makefile
> +	@cp ./build/ethermint  $(GOPATH)/bin/ethermint
It calls build, which will recompile, I used cp after build for the Git Commit version.

2017-05-23 14:37 UTC, merged

2017-05-23 14:37 UTC, adrianbrink commented
I've closed this, since I pulled this PR and merged it manually into unstable. Your comments are still there though