Preview release of 0.2.0
cosmos/ethermint-archive pull request #115
Opened 2017-05-28 08:14 UTC by adrianbrink

This PR request updates ethermint to its newest dependencies (go-ethereum and tendermint libs).

Once this lands, the focus will be on feature addition and bug fixes to get ethermint to be production ready.

2017-05-28 08:17 UTC, adrianbrink commented
@ebuchman

2017-05-28 16:46 UTC, illya13 commented on README.md
> +get attach http://localhost:8545
`geth` ?

2017-05-28 16:50 UTC, illya13 commented
Do we have CI build ?

2017-05-28 17:03 UTC, adrianbrink commented
@illya13 Yeah, that passed :-)

2017-05-28 17:03 UTC, adrianbrink commented on README.md
> +get attach http://localhost:8545
So, that people can interact with the ethereum node

2017-05-28 17:07 UTC, illya13 commented on README.md
> +get attach http://localhost:8545
You did not get me. There is a typo above. It should be `geth attach...` but we have `get attach`

2017-05-28 17:31 UTC, adrianbrink commented on README.md
> +get attach http://localhost:8545
oh right, fixed now :-)

2017-05-29 10:51 UTC, ramilexe requested changes
Please return fix for issue #14

2017-05-29 10:51 UTC, ramilexe commented on ethereum/backend.go
> -	// ethereum.EventMux().Post(core.ChainHeadEvent{currentBlock})
Why did you removed it? It is fix for https://github.com/tendermint/ethermint/issues/14

2017-05-29 10:51 UTC, ramilexe commented on ethereum/pending.go
> -	// TODO: allocate correct size in BeginBlock instead of using append
It is correct todo. Issue for that https://github.com/tendermint/ethermint/issues/72

2017-05-29 10:56 UTC, adrianbrink commented on ethereum/pending.go
> -	// TODO: allocate correct size in BeginBlock instead of using append
Yes, but I want to keep the todo's out of the codebase and on github instead.

2017-05-29 11:02 UTC, ramilexe approved these changes

2017-05-29 11:03 UTC, ramilexe commented on ethereum/pending.go
> -	// TODO: allocate correct size in BeginBlock instead of using append
Ok, got it

2017-05-29 12:46 UTC, merged