Parse configs from file as in geth
cosmos/ethermint-archive pull request #224
Opened 2017-08-03 22:50 UTC by nodar-chkuaselidze

Integrated codebase from `go-ethereum` for parsing `toml` files.

Now we can remove `configs` flag and expect it in the `home` and remove flags.
Where should I put example toml file ?

2017-08-04 22:33 UTC, odeke-em commented on cmd/utils/config.go
> +	UnlockAccounts []string `toml:",omitempty"`
Am not familiar with toml, but `toml:",omitempty"` for all the struct fields seems a little off to me.

2017-08-04 22:38 UTC, odeke-em commented on cmd/utils/config.go
> +// LoadConfig takes configuration file path and full configuration and applies file configs to it
Could we make this:
LoadConfig reads a configuration from disk and saves it into cfg

Minor not: also perhaps for easier parameter reading, make cfg something like
saveCfg or so and if that change applies, apply it to the comment above, please.

2017-08-04 22:41 UTC, odeke-em commented on cmd/utils/config.go
> +	err = tomlSettings.NewDecoder(bufio.NewReader(f)).Decode(cfg)
The signature http://godoc.org/github.com/naoina/toml#Config.NewDecoder is:
```go
func (*toml.Config).NewDecoder(io.Reader)
```
so I don't think we need the `bufio.NewReader(f)` since *os.File is already an `io.Reader`, unless there is something special about that decoder that it needs buffered io.

2017-08-04 22:41 UTC, odeke-em commented on cmd/utils/config.go
> +	// Add file name to errors that have a line number.
Nice!

2017-08-04 22:43 UTC, odeke-em commented on cmd/utils/config.go
> +	for i := range lines {
Might be a lot easier to read if for a non channel we didn't use `i := range lines`
so
```go
for i := 0; i < len(lines); i++
```

2017-08-04 22:47 UTC, odeke-em commented on cmd/utils/config.go
> +	out, err := tomlSettings.Marshal(&cfg)
Double indirection here, cfg is already a pointer i.e `*GethConfig`

2017-08-04 22:50 UTC, odeke-em commented on cmd/utils/config.go
> +func DumpConfig(cfg *GethConfig) error {
This is a nice helper but we could perhaps make it more configurable like this
```go
// FdumpTomlConfig serializes cfg to the output writer
func FdumpTomlConfig(f io.Writer, cfg *GethConfig) error {
   comment := ""
   if cfg.Eth.Genesis != nil {
      cfg.Eth.Genesis = nil
      comment += "# Note: this config doesn't contain the genesis block.\n\n"
   }

   out, err := tomlSettings.Marshal(cfg)
   if err != nil {
      return err
   }
   io.WriteString(w, comment)
   _, err = w.Write(out)
   return err
}
```
and then
```go
// DumpTomlConfig is a helper that serializes cfg to stdout
func DumpTomlConfig(cfg *GethConfig) error {
   return FdumpTomlConfig(os.Stdout, cfg)
}
```
and then we can also make unit tests to test that FdumpTomlConfig works well and matches our expectations.

2017-08-04 22:52 UTC, odeke-em requested changes
Hello @nodar-chkuaselidze, thank you for the PR! I am getting familiar with Ethermint, so please pardon me if I suggested the wrong thing, but I've left some comments that perhaps could be applied to the code.

2017-08-05 07:46 UTC, nodar-chkuaselidze commented
Well, `DumpConfig` and config parsing stuff is directly taken from `geth`. I was more concentrated on moving flags to config file and making them work, than improving go-ethereum's implementation.

2017-08-05 08:49 UTC, odeke-em commented
@nodar-chkuaselidze oh I see, my bad. In that case, please feel free to get your changes in for parity with geth, and then I'll submit a follow up PR adding the changes and tag you as a review if you are free. Am new around here so just learning how things work :)

2017-08-24 05:27 UTC, odeke-em reviewed
To avoid blocking you as mentioned in my last comment, I'll remove my requested changes :)

2017-08-27 11:26 UTC, adrianbrink commented
This PR will not be merged in this form. I would like to thank everyone that contributed, but the new proposed structure in #295 will tackle this separately.

2017-08-27 11:26 UTC, closed without merging