cmd/ethermint: use default Genesis when necessary
cosmos/ethermint-archive pull request #245
Opened 2017-08-13 07:03 UTC by odeke-em

Requires https://github.com/tendermint/tmlibs/pull/35
Fixes https://github.com/tendermint/ethermint/issues/244

Act like `tendermint init` so that if we don't have
a genesis-path, and also move to $HOME/.ethermint/keystore, the
files that are currently contained in
$GOPATH/src/github.com/tendermint/ethermint/setup/keystore

Therefore now `ethermint init` should be one step e.g
```shell
$ ethermint --datadir ~/.ethermint init
```
instead of the formerly tedious
```shell
$ cd $GOPATH/src/github.com/tendermint/ethermint
$ ethermint --datadir ~/.ethermint init setup/genesis.json
$ cp -r setup/keystore ~/.ethermint
```

2017-08-13 07:03 UTC, odeke-em commented
/cc @jaekwon @adrianbrink @ebuchman

2017-08-14 12:37 UTC, zramsay commented
can you edit https://github.com/tendermint/ethermint/blob/unstable/docs/getting-started.md as well, since it has the process this PR fixes

2017-08-14 20:59 UTC, odeke-em commented
Roger that @zramsay, I think that file was just added into the base branch,  sure I am rebasing and will add it in. Thanks for letting me know.

2017-08-15 17:14 UTC, ebuchman commented on cmd/ethermint/init.go
> +	genesis, err := common.ParseGenesisOrDefault(genesisPath)
As mentioned in the tmlibs PR, lets figure out how to bring this functionality in here

2017-08-15 17:19 UTC, adrianbrink commented on cmd/ethermint/init.go
> +	genesis, err := common.ParseGenesisOrDefault(genesisPath)
I second that. Ethermint should be the only place that needs to deal with go-ethereum.

2017-08-15 18:56 UTC, odeke-em commented on cmd/ethermint/init.go
> +	genesis, err := common.ParseGenesisOrDefault(genesisPath)
Gotcha gotcha, so initially I actually had it all contained in here, but I couldn't unit test the code since a bunch of code in here uses cli.NewApp which then directly dereferences os.Args[0] which unfortunately would make our unit tests iffy. cmd/ethermint/utils also coud not work due to the same problem. However, I can make a subdirectory in there, how about that?

2017-08-15 19:44 UTC, odeke-em commented on cmd/ethermint/init.go
> +	genesis, err := common.ParseGenesisOrDefault(genesisPath)
Umm, actually I don't know what on earth I was thinking, cmd/utils in this repo can accomodate the code and tests.

2017-08-15 19:45 UTC, odeke-em commented on cmd/ethermint/init.go
> +	genesis, err := common.ParseGenesisOrDefault(genesisPath)
@adrianbrink @ebuchman PTAL at the new update, I've added the parse code and tests to cmd/utils, and then I'll start pushing individual commits per round of review. Thanks!

2017-08-16 20:04 UTC, odeke-em commented
@adrianbrink @zramsay @ebuchman PTAL, I moved the code for ParseGenesisOrDefault into this repo.

2017-08-16 20:11 UTC, zramsay submitted a review, later dismissed
cool. excited to use this

2017-08-18 19:27 UTC, zramsay commented
what do folks think about a `--testnets` flag to spit out the required files?

2017-08-18 19:45 UTC, adrianbrink commented
I think it would be a great extension. @odeke-em Do you want to take a crack at adding that flag?

2017-08-20 22:03 UTC, odeke-em commented
@zramsay and @adrianbrink yes we can do that, could we spin up a new issue for that?

2017-08-20 22:15 UTC, adrianbrink commented
#282

2017-08-21 00:19 UTC, odeke-em commented
@zramsay @adrianbrink @ebuchman I've added the ability for ethermint to implicitly do `tendermint init` and `tendermint node` unless otherwise told not to, PTAL at the latest commit.

2017-08-22 17:56 UTC, zramsay commented on README.md
> +```
i'm thinking we should turn _on_ the behaviour with a `--start-tendermint` flag because we often use alternative directories (e.g. connecting to testnets & for dev)

2017-08-22 17:57 UTC, zramsay commented
see my one comment. I think the starting tendermint behaviour should be default off for now

2017-08-24 05:00 UTC, odeke-em commented on README.md
> +```
Roger that @zramsay, and in deed we could definitely document `--start-tendermint`. I'll update this right now, thanks!

2017-08-24 05:24 UTC, odeke-em commented
@zramsay thanks for the feedback, I've incorporated it in and pushed up a new commit. PTAL.

2017-08-25 13:04 UTC, zramsay commented on README.md
> +being starting by excluding the flag `--start-tendermint` for example
by excluding the flag `--include-tendermint` (not `--start-tendermint`)

2017-08-25 13:06 UTC, zramsay commented on cmd/ethermint/init.go
> +	log.Info("Invoking `tendermint", "args", args)
the logs look weird because of the backtick prefixed on tendermint. Can we append tendermint to the args instead and s/"args"/"command" maybe?

2017-08-25 13:08 UTC, zramsay commented on cmd/ethermint/ethermint.go
> +				log.Info("successfully invoked `tendermint node`", "args", tendermintArgs)
`succesfully` should be capitalized for consistency (first letter)

2017-08-25 13:09 UTC, zramsay commented on cmd/ethermint/init.go
> +	log.Info("Invoking `tendermint", "args", args)
or just put a backtick at suffix of tendermint

2017-08-25 13:12 UTC, zramsay commented on cmd/utils/flags.go
> +		Usage: "If set, it will invoke `tendermint init` and `tendermint node`" +
need a space between the backtick after `node` and `"`. Also the backticks around `tendermint init` do not show up in the helper message

2017-08-25 13:15 UTC, zramsay commented on cmd/utils/testdata/non-genesis.json
> +}
do we need to check in an extra file, or can the test just write it on the fly then remove it?

2017-08-25 14:20 UTC, zramsay commented
This PR half works. The `ethermint --datadir ~/.ethermint --include-tendermint init` works very well by making all the files in `~/.ethermint`. Then, running:

```
ethermint --include-tendermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin
```

leads to the logs hanging on:

```
INFO [08-25|10:10:50] Accepted a new connection                module=abci-server
INFO [08-25|10:10:50] Waiting for new connection...            module=abci-server
```

If I omit the `--include-tendermint` flag:

```
ethermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin
```

then run tendermint in a seperate window:

```
tendermint --home ~/.ethermint/tendermint/ node
```

the ethermint logs will hang on:

```
INFO [08-25|10:10:50] Waiting for tendermint endpoint to start err="Post http://localhost:46657/status: dial tcp 127.0.0.1:46657: getsockopt: connection refused"
```

and the tendermint logs panic:

``` 
E[08-25|14:10:50.643] Error on catchup replay. Proceeding to start ConsensusState anyway module=consensus err=EOF
E[08-25|14:10:51.546] enterPropose: Error signing proposal         module=consensus height=1 round=0 err="Error signing proposal: Step regression"
E[08-25|14:10:54.547] Error signing vote                           module=consensus height=1 round=0 vote="Vote{0:8723484F18E0 1/00/1(Prevote) 000000000000 %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)}" err="Error signing vote: Step regression"
E[08-25|14:11:08.264] Stopping abci.socketClient for error: EOF    module=abci-client connection=query
```

I also find the edits to the README would be a bit confusing to the beginner; I'm happy to re-write once the commands work

2017-08-25 14:22 UTC, zramsay commented
Also, what is supposed to happen with the tendermint logs when running with `--include-tendermint`?

2017-08-27 11:30 UTC, adrianbrink requested changes
Please see @zramsay comments.

2017-08-28 04:08 UTC, odeke-em commented on README.md
> +being starting by excluding the flag `--start-tendermint` for example
Oops, I don't know how I even used that flag. Thanks for the catch.

2017-08-28 04:09 UTC, odeke-em commented on cmd/ethermint/init.go
> +	log.Info("Invoking `tendermint", "args", args)
Roger that, I'll add the backtick to the suffix of tendermint.

2017-08-28 04:19 UTC, odeke-em commented on cmd/utils/flags.go
> +		Usage: "If set, it will invoke `tendermint init` and `tendermint node`" +
Roger that, updating, thanks.

2017-08-28 04:19 UTC, odeke-em commented on cmd/ethermint/ethermint.go
> +				log.Info("successfully invoked `tendermint node`", "args", tendermintArgs)
Roger that, updating it, thanks.

2017-08-28 04:21 UTC, odeke-em commented on cmd/utils/testdata/non-genesis.json
> +}
Good question, I'd rather have it on disk, as that simplifies tests.

2017-08-28 04:35 UTC, odeke-em commented
@zramsay in regards to https://github.com/tendermint/ethermint/pull/245#issuecomment-324934359
`
This PR half works. The ethermint --datadir ~/.ethermint --include-tendermint init works very well by making all the files in ~/.ethermint. Then, running:

ethermint --include-tendermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin
leads to the logs hanging on:

INFO [08-25|10:10:50] Accepted a new connection                module=abci-server
INFO [08-25|10:10:50] Waiting for new connection...            module=abci-server
`
I can't yet reproduce the hang, please see https://asciinema.org/a/4bSXNS9WeDjxOcWpQpuO8wFk0.

Perhaps it might take sometime for `tendermint node` to be invoked but that's part of the setup process that we'd still get if we invoked it in a separate terminal as you did.

In regards to
```
he ethermint logs will hang on:

INFO [08-25|10:10:50] Waiting for tendermint endpoint to start err="Post http://localhost:46657/status: dial tcp 127.0.0.1:46657: getsockopt: connection refused"
and the tendermint logs panic:

E[08-25|14:10:50.643] Error on catchup replay. Proceeding to start ConsensusState anyway module=consensus err=EOF
E[08-25|14:10:51.546] enterPropose: Error signing proposal         module=consensus height=1 round=0 err="Error signing proposal: Step regression"
E[08-25|14:10:54.547] Error signing vote                           module=consensus height=1 round=0 vote="Vote{0:8723484F18E0 1/00/1(Prevote) 000000000000 %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)}" err="Error signing vote: Step regression"
E[08-25|14:11:08.264] Stopping abci.socketClient for error: EOF    module=abci-client connection=query
```
I don't think that crash is related to this change, perhaps we might have to do some more debugging on edge cases with Tendermint and Ethermint. In the past I've experienced some problems which I reported via the Slack channel `ethermint` but due to having to move onto separate issues, just removed my `$HOME/.ethermint`  directory and then started afresh.

In regards to the documentation, in deed, please do help, you are great at articulating prose and this PR and repo could use that.

2017-08-28 04:36 UTC, odeke-em commented
@zramsay in regards to https://github.com/tendermint/ethermint/pull/245#issuecomment-324934359
```
This PR half works. The ethermint --datadir ~/.ethermint --include-tendermint init works very well by making all the files in ~/.ethermint. Then, running:

ethermint --include-tendermint --datadir ~/.ethermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin
leads to the logs hanging on:

INFO [08-25|10:10:50] Accepted a new connection                module=abci-server
INFO [08-25|10:10:50] Waiting for new connection...            module=abci-server
```
I can't yet reproduce the hang, please see https://asciinema.org/a/4bSXNS9WeDjxOcWpQpuO8wFk0.

Perhaps it might take sometime for `tendermint node` to be invoked but that's part of the setup process that we'd still get if we invoked it in a separate terminal as you did.

In regards to
```
he ethermint logs will hang on:

INFO [08-25|10:10:50] Waiting for tendermint endpoint to start err="Post http://localhost:46657/status: dial tcp 127.0.0.1:46657: getsockopt: connection refused"
and the tendermint logs panic:

E[08-25|14:10:50.643] Error on catchup replay. Proceeding to start ConsensusState anyway module=consensus err=EOF
E[08-25|14:10:51.546] enterPropose: Error signing proposal         module=consensus height=1 round=0 err="Error signing proposal: Step regression"
E[08-25|14:10:54.547] Error signing vote                           module=consensus height=1 round=0 vote="Vote{0:8723484F18E0 1/00/1(Prevote) 000000000000 %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)}" err="Error signing vote: Step regression"
E[08-25|14:11:08.264] Stopping abci.socketClient for error: EOF    module=abci-client connection=query
```
I don't think that crash is related to this change, perhaps we might have to do some more debugging on edge cases with Tendermint and Ethermint. In the past I've experienced some problems which I reported via the Slack channel `ethermint` but due to having to move onto separate issues, just removed my `$HOME/.ethermint`  directory and then started afresh.

In regards to the documentation, in deed, please do help, you are great at articulating prose and this PR and repo could use that.

2017-08-28 04:38 UTC, odeke-em commented
@zramsay in regards to https://github.com/tendermint/ethermint/pull/245#issuecomment-324934842
```
Also, what is supposed to happen with the tendermint logs when running with --include-tendermint? I wanna see them
```
that's a great question, however I believe that trying to merge tendermint and ethermint logs to stdout all together is going to complicate things. I'd propose that in the next iterations we can add a flag to redirect tendermint logs to a location, but IMHO after the first phase, so that we can get this off the ground first and merged in.

2017-08-28 16:12 UTC, zramsay commented
hmm, so I updated to tendermint 0.10.3 and it didn't work once now it works reliably. :+1: from me, this is good to go

2017-08-28 16:43 UTC, adrianbrink commented
It doesn't work for me:

I run `make build` to build it.

The I initialise ethermint:
```
/build/ethermint --datadir ~/.ethermint-test --include-tendermint init setup/genesis.json
```

and finally start it with:
```
./build/ethermint --datadir ~/.ethermint-test --include-tendermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin --unlock 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc
```

I then get this error:
```
Server listen tcp 0.0.0.0:46658: bind: address already in use
```

Do you know where this comes from?

2017-08-28 17:07 UTC, adrianbrink commented
I've pushed this again on a branch so that I could rebase it on develop.

2017-08-28 17:59 UTC, odeke-em commented
@adrianbrink you can rebase it though on this branch, and let me do so right now too.

2017-08-28 18:02 UTC, odeke-em commented
@adrianbrink rebase done.

2017-08-28 18:03 UTC, odeke-em commented
@adrianbrink https://github.com/tendermint/ethermint/pull/245#issuecomment-325407448
```
and finally start it with:

./build/ethermint --datadir ~/.ethermint-test --include-tendermint --rpc --rpcaddr=0.0.0.0 --ws --wsaddr=0.0.0.0 --rpcapi eth,net,web3,personal,admin --unlock 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc
I then get this error:

Server listen tcp 0.0.0.0:46658: bind: address already in use
Do you know where this comes from?
```
Looks like an instance of ethermint is already running.

2017-08-28 19:39 UTC, adrianbrink commented
@odeke-em One last thing, can you change `--include-tendermint` to `--with-tendermint` and then I can merge this.

2017-08-28 19:41 UTC, odeke-em commented
That's a great name suggestion actually, kuddos for the simplification!

2017-08-28 19:52 UTC, GitCop commented
There were the following issues with your Pull Request

 * Commit: d2d37adcfe974d9db3f2458ae057cd26b472517a
  * Your subject line is longer than 72 characters

Line length is maximum 72 characters.

Guidelines are available at https://github.com/tendermint/ethermint

---
This message was auto-generated by https://gitcop.com

2017-08-28 19:53 UTC, odeke-em commented
Thanks @adrianbrink @zramsay @ebuchman for the review! I've squashed my commits into one and ready for the merge.

2017-08-28 21:26 UTC, zramsay commented
gitcop not happy, and also could you edit the original PR message since a bunch of stuff has changed & it's a nice reference/summary of the changes

2017-08-29 07:09 UTC, adrianbrink approved these changes

2017-08-29 07:09 UTC, adrianbrink commented
@odeke-em Last thing is to fix the commit message :-)

2017-08-29 07:14 UTC, odeke-em commented
Oops, @zramsay and @adrianbrink, am just seeing this. Let me fix that message.

2017-08-29 08:48 UTC, merged

2017-08-29 08:50 UTC, odeke-em commented
Thanks y'all for the review and merge @adrianbrink @zramsay @ebuchman!