WIP: Use correct syncing status from Tendermint core
cosmos/ethermint-archive pull request #249
Opened 2017-08-14 07:09 UTC by adrianbrink

Signed-off-by: Adrian Brink <adrian@brink-holdings.com>

This is work in-progress. I have opened this in order to show what still needs to be pulled into the `unstable` branch from before the big revert.

2017-08-14 21:37 UTC, odeke-em reviewed
My comments are just minor nits.

2017-08-14 21:37 UTC, odeke-em commented on app/test/helpers.go
> +		return nil, errors.New("BigInt convertation error")
s/convertation/conversion/g

2017-08-14 21:37 UTC, odeke-em commented on ethereum/test/api_test.go
> +		t.Errorf("Error calling Syncing: %+v", err)
t.Fatalf

2017-08-14 21:37 UTC, odeke-em commented on app/test/helpers.go
> +	genesisPath := filepath.Join(gopath, "src/github.com/tendermint/ethermint/setup/genesis.json")
Not important right now, but perhaps sometime later on, it might be helpful for us to copy the genesis file to something like `testdata/genesis.json`

2017-08-18 19:12 UTC, odeke-em commented on ethereum/api.go
> +func (s *PublicEthereumAPI) GasPrice(ctx context.Context) (*big.Int, error) {
Could we perhaps keep this method name as SuggestPrice instead?

2017-08-18 19:23 UTC, odeke-em requested changes
Thanks for the PR @adrianbrink, I've added some comments to the review. PTAL

2017-08-18 19:23 UTC, odeke-em commented on ethereum/api.go
> +func (s *PublicEthereumAPI) GasPrice(ctx context.Context) (*big.Int, error) {
Could we keep this method name as SuggestPrice instead?

2017-08-18 19:23 UTC, odeke-em commented on ethereum/api.go
> +func (s *PublicEthereumAPI) Syncing() (interface{}, error) {
Could we fix this signature to `(bool, error)`? The method name as well as comment dictates that but also the deference so we can make that. Also perhaps we can use a more direct name.
```go
func (s *PublicEthereumAPI) InFastSync() (status bool, err error) {
    res, err := s.client.Status()
    if err == nil && res != nil {
       status = res.Syncing
    }
    return status, err
}
```

2017-08-18 19:23 UTC, odeke-em commented on ethereum/api.go
> +func (s *PublicEthereumAPI) ProtocolVersion() hexutil.Uint {
How come the use of hexutil.Uint?
Is PublicEthereumAPI satisfying an Ethereum API? If so could we make that implicit by a compile type assertion e.g
```go
var _ theInterfaceToSatisfy = (*PublicEthereumAPI)(nil)
```

2017-08-18 20:02 UTC, adrianbrink commented on ethereum/api.go
> +func (s *PublicEthereumAPI) GasPrice(ctx context.Context) (*big.Int, error) {
These names are what they are called on the go-ethereum side and I don't want to change them.

2017-08-18 20:03 UTC, adrianbrink commented on ethereum/api.go
> +func (s *PublicEthereumAPI) Syncing() (interface{}, error) {
These names are what they are called on the go-ethereum side and I don't want to change them.

2017-08-18 20:08 UTC, adrianbrink commented
This is unsafe to do.

go-ethereum adds all RPC apis when this method is called here: https://github.com/tendermint/go-ethereum/blob/master/eth/backend.go#L244

However, the returned slice contains two PublicEthereumAPI instances. 
The first one is added by this [method](https://github.com/tendermint/go-ethereum/blob/master/internal/ethapi/backend.go#L70) and is the one we want to override.

The second one is added locally in backend.go#L255 and is defined here: https://github.com/tendermint/go-ethereum/blob/master/eth/api.go#L50

The problem is that the current way we override that API is broken, since we are replacing the API with the Coinbase() method with the one for ProtocolVersion(). 

I don't currently know a way to directly override the first one, since they are called the same name, have the same fields and we can't check for the type since it is defined in the internal package.

Any ideas would be welcome.

2017-08-18 20:11 UTC, adrianbrink commented
The question is how can I distinguish between [this](https://github.com/tendermint/go-ethereum/blob/master/internal/ethapi/api.go#L53) and [this](https://github.com/tendermint/go-ethereum/blob/master/eth/api.go#L50).

2017-08-18 20:16 UTC, odeke-em commented on ethereum/api.go
> +func (s *PublicEthereumAPI) Syncing() (interface{}, error) {
Alright, gotcha, this is why I was suggesting that perhaps if we are satisfying an interface from ethereum, that we should use a compile time assertion in the file.

2017-08-19 16:46 UTC, adrianbrink commented on ethereum/api.go
> +func (s *PublicEthereumAPI) Syncing() (interface{}, error) {
These are all structs that we are simply reimplementing and they only need to conform to [interface{}](https://github.com/tendermint/go-ethereum/blob/master/rpc/types.go#L34).

2017-08-19 16:48 UTC, adrianbrink commented
This works, but we need to document the invariants that we are assuming when overriding.

2017-08-20 15:52 UTC, adrianbrink commented on ethereum/api.go
> +func (s *PublicEthereumAPI) Syncing() (interface{}, error) {
However the RPC is relying on the names, so we cannot change them.

2017-08-29 11:15 UTC, adrianbrink commented
This feature will be implemented in the larger redesign when we implement the RPC ourselves.

2017-08-29 11:15 UTC, closed without merging