Set NoUSB to prevent nondeterministic bug
cosmos/ethermint-archive pull request #352
Opened 2017-11-22 00:29 UTC by jaekwon

'make test' was randomly failing without this change.

2017-11-22 03:13 UTC, ebuchman approved these changes
Huh. What is this config for - hardware wallets ?

2017-11-22 09:20 UTC, kesar approved these changes

2017-11-22 10:40 UTC, adrianbrink commented
What kind of failure did you get from `make test`. I haven't experienced this non-determinism before.

2017-11-22 22:05 UTC, adrianbrink requested changes
Could you post one of those test failures?

I don't think we want to permanently turn this off because otherwise none of the USB wallets would work.

If this is a persistent issue in the tests we can only turn it off during those.

2017-11-22 22:06 UTC, adrianbrink commented
@ebuchman Yes, this disables the node from accepting connections from hardware wallets.

2017-11-24 19:36 UTC, jaekwon commented
`for i in {0..100}; do make test; done` shows the issue.
```--> Running go test
go test ./app/... ./cmd/... ./ethereum/... ./strategies/... ./types/... ./version/...
ok  	github.com/tendermint/ethermint/app	22.195s
?   	github.com/tendermint/ethermint/cmd/ethermint	[no test files]
ok  	github.com/tendermint/ethermint/cmd/utils	0.263s
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fff9ef7ab00]

runtime stack:
runtime.throw(0x48fb6bf, 0x2a)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/signal_unix.go:274 +0x2db

goroutine 12 [syscall, locked to thread]:
runtime.cgocall(0x4715a80, 0xc420038ad8, 0xc42007e4e0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/cgocall.go:131 +0xe2 fp=0xc420038a98 sp=0xc420038a58
github.com/tendermint/ethermint/vendor/github.com/karalabe/hid._Cfunc_hid_enumerate(0x0, 0x0)
	github.com/tendermint/ethermint/vendor/github.com/karalabe/hid/_obj/_cgo_gotypes.go:248 +0x4e fp=0xc420038ad8 sp=0xc420038a98
github.com/tendermint/ethermint/vendor/github.com/karalabe/hid.Enumerate(0xc400000000, 0x0, 0x0, 0x0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/karalabe/hid/hid_enabled.go:70 +0x71 fp=0xc420038ba8 sp=0xc420038ad8
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/usbwallet.(*LedgerHub).refreshWallets(0xc42009c2d0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/usbwallet/ledger_hub.go:120 +0xd5 fp=0xc420038fa8 sp=0xc420038ba8
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/usbwallet.(*LedgerHub).updater(0xc42009c2d0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/usbwallet/ledger_hub.go:206 +0x68 fp=0xc420038fd8 sp=0xc420038fa8
runtime.goexit()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420038fe0 sp=0xc420038fd8
created by github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/usbwallet.(*LedgerHub).Subscribe
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/usbwallet/ledger_hub.go:188 +0x133

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42021e410, 0x48f5996, 0x22, 0x4a2f750, 0x405d001)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc42021e410)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:882 +0x67
testing.tRunner(0xc42021e410, 0xc4204b5de0)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:657 +0x96
testing.runTests(0xc420186d80, 0x4f16220, 0x3, 0x3, 0x4e3dcc0)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc4205f7f20, 0xc4204b5f20)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:822 +0xfc
main.main()
	github.com/tendermint/ethermint/ethereum/_test/_testmain.go:46 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [chan receive]:
github.com/tendermint/ethermint/vendor/github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x4f39520)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/rcrowley/go-metrics/meter.go:221 +0x4c
created by github.com/tendermint/ethermint/vendor/github.com/rcrowley/go-metrics.NewMeter
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/rcrowley/go-metrics/meter.go:40 +0x127

goroutine 7 [chan receive]:
github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc420012a00)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify/tree_recursive.go:125 +0x63
created by github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify.newRecursiveTree
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify/tree_recursive.go:119 +0x1d4

goroutine 8 [syscall, locked to thread]:
github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify/_obj/_cgo_gotypes.go:214 +0x41
github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify.init.1.func1()
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:68 +0x6f
created by github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify.init.1
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:70 +0x4e

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/usr/local/Cellar/go/1.8.1/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/Cellar/go/1.8.1/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 10 [select]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc4200f12e0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:91 +0x622
created by github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:52 +0x5f

goroutine 11 [select]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).updater(0xc42009c1e0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:203 +0x18d
created by github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).Subscribe
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:190 +0x133

goroutine 13 [select]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc42021e340)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/manager.go:95 +0x40e
created by github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts.NewManager
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/manager.go:68 +0x5ed

goroutine 35 [semacquire]:
sync.runtime_Semacquire(0xc4201aa1b4)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4201aa1a8)
	/usr/local/Cellar/go/1.8.1/libexec/src/sync/waitgroup.go:131 +0x7a
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/p2p.(*Server).Stop(0xc4201aa000)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/p2p/server.go:339 +0xb8
github.com/tendermint/ethermint/ethereum.(*Node).Start(0xc42019e240, 0xc42019e240, 0x0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/ethereum/node.go:35 +0x6c
github.com/tendermint/ethermint/ethereum.TestEnsureDisabledEthereumP2PStack(0xc42006d2b0)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/ethereum/node_test.go:52 +0x152
testing.tRunner(0xc42006d2b0, 0x4a2f750)
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/Cellar/go/1.8.1/libexec/src/testing/testing.go:697 +0x2ca

goroutine 36 [select]:
github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc42010e800)
	/Users/jae/gocode/src/github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore/watch.go:91 +0x622
created by github.com/tendermint/ethermint/vendor/github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
	/Users/jae/gocod [...]

2017-11-24 19:43 UTC, jaekwon commented
I believe the error actually changes each time it fails.

2017-11-25 11:40 UTC, kesar commented
I wasn't able to reproduce it with the loop test. Could it be your Go version 1.8.1 ?
```
➜  ethermint git:(master) ✗ go version
go version go1.8.3 darwin/amd64
```

2017-11-26 15:39 UTC, adrianbrink commented
Okay, so I can reproduce the error on `go1.8.3` and `go1.9.3` by running `make test` on `develop` a lot of times. It shows up in roughly 2% of the cases and hence I'm not surprised that this doesn't get caught by CircleCi.

I've been running the `go-ethereum` test-suite all day, but I can't observer any failure that is directly related to USBDevices or HID.

We need to look into [this](https://github.com/tendermint/ethermint/blob/master/cmd/utils/utils.go) and [this](https://github.com/tendermint/ethermint/blob/master/cmd/ethermint/ethermint.go) . 

My assumption is that `go-ethereum` works and `Ethermint` introduces some weird interaction that causes these rare test failures. 

Disabling the USB device generally isn't a great solution, because it would mean that hardware wallets would no longer work with `ethermint`. 
The question is though, whether we need hardware wallet support directly in `ethermint` or whether it can happily live in the client side code beyond the Web3 RPC connection.

2018-07-11 18:26 UTC, closed without merging