Add docker-compose.yaml
cosmos/ethermint-archive pull request #426
Opened 2018-07-13 21:29 UTC by jackzampolin

Add a docker compose file and instructions on how/why to run. Also move `blockchain` into `data/blockchain`.

cc @alexanderbez and @AlexeyAkhunov

2018-07-13 21:38 UTC, alexanderbez commented
@jackzampolin tbh, I don't think we need this atm. This is really just meant for @AlexeyAkhunov and I to quickly smoke test. Eventually the docker-compose file with actually start a local few node ethermint network.

2018-07-13 21:40 UTC, jackzampolin commented
@alexanderbez I get that. I would also like to be able to quickly smoke test, and having those instructions on the repo would be great. They don't need to be through a `docker-compose` however so I can pull that out, but I'm happy to continue updating that as work progresses.

2018-07-13 21:49 UTC, alexanderbez commented
@jackzampolin yeah that's cool with him. Remove the compose file (for now) and just keep the instructions in the README 👍

2018-07-13 22:03 UTC, jackzampolin commented
Fixed!

2018-07-14 02:08 UTC, alexanderbez requested changes
Thanks @jackzampolin, left two minor suggestions 👍

2018-07-14 02:08 UTC, alexanderbez commented on .gitignore
> +*.db
I think we can avoid both of these. We need to allow this to be configurable (the datadir)

2018-07-14 02:08 UTC, alexanderbez commented on README.md
> +balance of 0x756F45E3FA69347A9A973A725E3C98bC4db0b5a0: 200000000000000000000
I think having the command is enough for now. This was all thrown together rather quickly, so I wouldn't rely or worry much about the exact output.

2018-07-16 14:34 UTC, jackzampolin commented on README.md
> +balance of 0x756F45E3FA69347A9A973A725E3C98bC4db0b5a0: 200000000000000000000
Done!

2018-07-16 14:35 UTC, jackzampolin commented on .gitignore
> +*.db
When I ran the command I got all that stuff showing up in my project dir. I was just adding them so they don't get picked up in git history. Is that an issue?

2018-07-16 14:38 UTC, alexanderbez commented on .gitignore
> +*.db
Yeah cause that's where Alexey has them by default. I don't want to pollute this file with that stuff unless it's going to be permanent (which its not). You have two options:

1. Just keep deleting them
2. Add them to your personal global gitignore:
```
$ git config --global core.excludesfile ~/.gitignore_global
```
`~/.gitignore_global` will contain all the stuff you dont wanna commit 👍

2018-07-16 14:49 UTC, jackzampolin commented on .gitignore
> +*.db
pulled them out and added issue to track data directory work: https://github.com/cosmos/ethermint/issues/430

2018-07-16 14:52 UTC, alexanderbez approved these changes
Thans @jackzampolin 🙌

2018-07-16 14:52 UTC, merged