WIP: Tx Structure
cosmos/ethermint-archive pull request #451
Opened 2018-07-20 18:40 UTC by AdityaSripal

Addresses #431 

My initial idea of how inner transactions can work

 

* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))
* [ ] Added appropriate labels to PR (ex. wip, ready-for-review, docs)

2018-07-20 18:41 UTC, AdityaSripal commented on types/tx.go
> +	// Must somehow set ethTx.data.{V, R, S}
Need feedback on this. Currently can't find a better way to copy V, R, and S from ethermint/Transaction to ethereum/Transaction

2018-07-20 18:43 UTC, AdityaSripal commented on auth/ante.go
> +	// TODO: Validate Signatures
Need feedback on this. Should figure out some sort of SignDoc for signers.

Do we want the Ethereum tx signer to also sign these msgs? Should we require that Ethereum signer is also the first signer of InnerTx.GetRequiredSigners? If so, can we omit his/her signature from the required ones in inner tx?

2018-07-24 16:01 UTC, ebuchman commented on auth/ante.go
> +	// TODO: Validate Signatures
Maybe we don't need an external signer for txs sent to the special SDK address.

2018-07-24 18:04 UTC, alexanderbez requested changes
Looks great @AdityaSripal! Left some remarks and followup for you. In addition, I did a bit of cleanup. I think we're pretty close 👍

2018-07-24 18:04 UTC, alexanderbez commented on types/errors.go
> +// Error constructors
Can we add whitespace and document `ErrInvalidValue`?

2018-07-24 18:04 UTC, alexanderbez commented on types/tx.go
> +type InnerTransaction struct {
Can we possibly rename `InnerTransaction` and related nomenclature (e.g. handlers). Maybe `EmbeddedTx` or `SDKTx`?

2018-07-24 18:04 UTC, alexanderbez commented on types/tx.go
> +	txDataMarshaling struct {
I looked through the geth code and I'm not sure we actually need this structure? Correct me if I'm wrong :-)

2018-07-24 18:04 UTC, alexanderbez commented on types/tx.go
> +	Transaction struct {
Why does `Transaction` implement the `sdk.Tx` and `sdk.Msg` interfaces and not just
the `sdk.Tx` interface? It's a bit confusing on the surface. If we are to do this, it seems to make more sense doing it on the embedded SDK tx, no?

2018-07-24 18:04 UTC, alexanderbez commented on auth/ante.go
> +package auth
I think we should find a better place for `auth/`. What do you see the scope of auth being? It
does not seem to be a custom module. I think it should be nested under a parent package (i.e. `handlers`).

2018-07-24 18:04 UTC, alexanderbez commented on auth/ante.go
> +	// TODO: Validate Signatures
Agreed with @ebuchman. It seems that an external signer should only be needed for Ethereum txs and can be omitted for SDK routed txs which would inherently require their own set of signatures.

2018-07-24 18:04 UTC, alexanderbez commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
- I think this can be moved to after the check for `IsSDKTx`.
- Should we verify that this is a `EIP155Signer`?
- Generally, I feel like majority of this logic can be abstracted out a bit. Seems the only things you need upfront are `ctx` and the `txData`. Once you have that, depending on the result of `mintTx.IsSDKTx`, you can delegate certain calls.

2018-07-24 18:04 UTC, alexanderbez commented on auth/ante.go
> +			return ctx, sdk.NewError(2, 101, err.Error()).Result(), true
Are these integers constants anywhere? If so, can we use those instead?

2018-07-24 18:31 UTC, AdityaSripal commented on auth/ante.go
> +	// TODO: Validate Signatures
So inner Tx's don't have signatures? I don't think that will work because SDK msg's have expected signers.

This is fine in the case where the sdk msgs only have one signer, because we can just enforce that the ETH tx signer is the address that msg.GetSigner expected.

In the case where there are multiple required signers, this no longer works because there is no way i know to include the other signers. Maybe using multisig works? Tho i found nothing about it in the geth repo yet.

2018-07-24 18:41 UTC, AdityaSripal commented on types/tx.go
> +	Transaction struct {
Because Ethereum didn't create their `Transaction` with cosmos-sdk interfaces in mind, i don't think there's a clean way to take the outer tx structure and seperate it into `sdk.Tx` and `sdk.Msg`. However, we still want our outer Ethereum Tx through `Antehandler` and a `Handler` both of which expect a `sdk.Tx` and `sdk.Msg` respectively. Thus, the only way i can think of getting this to work is to have Eth Tx implement both `sdk.Tx` and `sdk.Msg` interfaces. Happy to hear other suggestions tho

We don't need to do this at all to the embedded SDK tx. The sdk msg by definition already implement sdk.Msg cleanly, we can just wrap it with some authentication to create a struct that implements sdk.Tx easily.

2018-07-24 18:44 UTC, AdityaSripal commented on auth/ante.go
> +package auth
I was planning on putting both the antehandler and the handler into `auth` package but, maybe just renaming auth package to handlers is sufficient. Not sure a nested package is needed.

2018-07-24 18:56 UTC, AdityaSripal commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
- My thinking was that if the signing of outer tx fails then we don't care about processing inner tx. I guess we can route to the sdkTxHandler and check the sig there, but i don't see how that's better.
- Is the plan to support just one type of signer? That makes things a lot simpler, but from my understanding, we want to all Ethereum transactions from Genesis to run successfully on Ethermint. To do that, I create whatever signer is necessary at the given blockheight and validate the signature using the appropriate signer. I realize now, we want to have both my case of supporting all signers and your case of supporting only EIP155Signers. We can create a Ethermint App boolean attribute to decide which case this is.
- Definitely agree this can be cleaned up and abstracted, will work on that.

2018-07-24 19:51 UTC, alexanderbez commented on auth/ante.go
> +	// TODO: Validate Signatures
No, I think the idea was:
- If eth tx, it should have a single signature
- If sdk tx, it should all required signatures part of the embedded sdk tx

2018-07-24 20:40 UTC, alexanderbez commented on types/tx.go
> +	Transaction struct {
> Because Ethereum didn't create their `Transaction` with cosmos-sdk interfaces in mind, i don't think there's a clean way to take the outer tx structure and seperate it into `sdk.Tx` and `sdk.Msg`.

Yeah, I do understand that. I went through the handler/router cases in my head and can't think of a cleaner way right now. I think this is fine for us now 👍

2018-07-24 20:42 UTC, alexanderbez commented on auth/ante.go
> +package auth
I imagine we'll have other handlers (e.g. `EthereumHandler`). Where would these live?

2018-07-24 20:44 UTC, alexanderbez commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
See comments above :-)

2018-07-24 20:46 UTC, alexanderbez commented
@AdityaSripal addressed followups. I think all that is left is just addressing some nomenclature changes + adding docs and signature stuff.

2018-07-24 22:10 UTC, jackzampolin commented
Docs or the feature isn't complete!

2018-07-24 22:28 UTC, AdityaSripal commented on auth/ante.go
> +	// TODO: Validate Signatures
> If sdk tx, it should have all required signatures part of the embedded sdk tx

Ok i understand bucky's suggestion now, no outer signer for sdk tx. It doesn't work with the current way i handle gas, as I expect the outer Tx sender to pay the fee for processing the entire Tx (outer and inner). Currently I take the gasLimit sent in to the outer ETH Tx, and then pass it into context for processing the inner Tx's with that gas amount.
If we choose to do this, we must have someone sign the ETH Tx otherwise anyone can cause the first signer of the inner Tx to pay exorbitant fees by simply increasing those fields arbitrarily.

We could say that for sdk tx, we have no fee on the outer tx and expect fees to be included in the inner sdk Tx. ~~Not sure which method is better.~~
NVM: DOS vector would be introduced by spamming sdk tx with bad payload

@ebuchman @alexanderbez

2018-07-24 22:39 UTC, jackzampolin commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
We need to support hard spoon from genesis in order to properly calculate token balances right? Sounds like we need to support different signers?

2018-07-24 22:45 UTC, alexanderbez commented on auth/ante.go
> +	// TODO: Validate Signatures
@AdityaSripal right, as I see it, if the `Transaction` is an SDK tx and as such it should have no "outer" signer. As a result, the `gasLimit` should be ignored and we should delegate fee logic to the inner (SDK) tx. This makes sense to me at a high level -- correct me if I'm wrong @ebuchman.

2018-07-24 22:47 UTC, alexanderbez commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
@jackzampolin, mhmmm I don't think so? The latest state at some block `n` should have all the balances at that point no?

2018-07-24 23:03 UTC, AdityaSripal commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
I don't believe the latest state at block `n` is extractable in Ethereum, without running through all transactions from Genesis till block `n`. @jackzampolin , let me know if im wrong

2018-07-24 23:04 UTC, alexanderbez commented on auth/ante.go
> +	// TODO: Validate Signatures
After more discussion, it seems wise to always have a signer on the actual entire `Transaction`. In the case of an SDK tx, the outter tx will have a signer and that signer should be the expected fee payer of the inner (SDK) tx. This keeps inline with the SDK logic (first signer == fee payer).

The inner tx signers will also include the outer signer. This will add a few extra bytes to the `payload`, but it will make the code easier to read and reason about. If it really becomes a bottleneck, we can remove that extra sig from the inner sigs.

2018-07-24 23:06 UTC, alexanderbez commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
Mhmmm, I know for a fact we do not want to deal with and handle Eth's forking logic and we only want to support chain-id based sigs.

2018-07-24 23:23 UTC, jackzampolin commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
My understanding is that to compute a token balance you need to run all the transactions since the token was created. Otherwise you won't be able to generate the balances.

2018-07-24 23:29 UTC, alexanderbez commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
Let's punt this for now and chat about this in next week's call. We have enough to build until then.

/cc @ebuchman

2018-07-30 19:22 UTC, jackzampolin commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
cc @zmanian

2018-07-30 20:27 UTC, zmanian commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
Can't we just import the output of https://wiki.parity.io/CLI-Sub-commands#export-state into ethermint rather than replaying old blocks?

This would also eliminate the need to parse old signatures at all. Also you could stand up hard spoon chains instantly.

2018-07-30 20:39 UTC, alexanderbez commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
Yeah @zmanian with used geths `export` functionality to run the benchmarks. From today's call we agreed to only support EIP155 sigs.

2018-07-30 20:40 UTC, zmanian commented on auth/ante.go
> +		signer := ethtypes.MakeSigner(config, big.NewInt(ctx.BlockHeight()))
Okay yay!

2018-07-30 20:55 UTC, jackzampolin commented
So sounds like we only need to support `EIP155Signer` as we can assume that txns in the chain that we are importing are valid. 

Another item of note is that we are blocking on a review from @ebuchman and/or @jaekwon on the direction taken by this PR on two items:

- ETH Tx structure and handling w/in the SDK types
- Fee structure and handling w/in the SDK types

2018-07-31 01:34 UTC, AdityaSripal commented
Hey @alexanderbez , quick review before moving onto tests and docs will be helpful!

2018-08-01 03:31 UTC, alexanderbez requested changes
@AdityaSripal I left three small minor remarks, but otherwise, looks great!

Could you:
* Address these remarks
* Remove the notion of the custom `Account` type and just use the SDK's account.
* Implement unit tests

I've also gone ahead and squashed the commits and rebased atop of `master` for your convenience.

2018-08-01 03:31 UTC, alexanderbez commented on handlers/ante.go
> +		signBytes := tx.SignBytes(ctx.ChainID(), seq)
@AdityaSripal do we not also need the account number? Since we will be using the account structure from the SDK, we can literally just get the entire account, and then get the number and sequence/nonce.

2018-08-01 03:31 UTC, alexanderbez commented on types/tx.go
> +func (tx Transaction) GetSigners() []sdk.AccAddress {
Since we do a no-op for `Transaction#GetSignBytes`, do we need to implement this? How and in what context will this be used?

2018-08-01 03:31 UTC, alexanderbez commented on handlers/ante.go
> +		_, err := signer.Sender(&ethTx)
I can't seem to recall where geth does this? Do we need to validate the signature bytes and the actual signer? Or does `Sender` already do this?

> TODO: Maybe we should increment AccountNonce in mapper here as well?
In Gaia, it seems the sequence number increment is only persisted if signature validation passes, is that correct? If so, we can skip here.

2018-08-01 20:58 UTC, AdityaSripal commented on handlers/ante.go
> +		signBytes := tx.SignBytes(ctx.ChainID(), seq)
Yup, this is what I will do. We only need account number if we decide to prune state. May as well include it for now so we can prune in future.

2018-08-01 20:59 UTC, AdityaSripal commented on types/tx.go
> +func (tx Transaction) GetSigners() []sdk.AccAddress {
Don't need to implement this, I don't use it in antehandler. I just did because the data is available (assuming tx is signed)

2018-08-01 21:06 UTC, AdityaSripal commented on handlers/ante.go
> +		_, err := signer.Sender(&ethTx)
core/types/transaction_signing.go

Yea, what it does is it recovers the address from the signature and then loads it into the from field if its not there already.

Correct, if checkTx fails then nothing gets written to state. What are we skipping?

2018-08-02 17:50 UTC, alexanderbez commented on types/tx.go
> +func (tx Transaction) GetSigners() []sdk.AccAddress {
Cool, I guess let's be consistent and also have it be a no-op?

2018-08-02 17:51 UTC, alexanderbez commented on handlers/ante.go
> +		_, err := signer.Sender(&ethTx)
Skip incrementing the nonce.

2018-08-03 19:52 UTC, jackzampolin commented
Final review blocking on testing the following per @AdityaSripal:

```
1. Test embedded tx with an actual SDK msg inside. Currently I just encode empty msg list into SDK tx. Will involve registering an sdk msg, possibly into seperate test codec.
2. Check that wrong account/sequence number fails.
3. Check that sequence number increments correctly
4. Very basic app/ level test
```

2018-08-06 14:41 UTC, alexanderbez commented
@jackzampolin I will pick up from here and merge once complete 👍

2018-08-06 19:19 UTC, jackzampolin approved these changes

2018-08-08 19:36 UTC, alexanderbez commented
@AdityaSripal please give this a quick look over before I merge. Major changes:

* Removed ante handler unit tests (will address in another issue -- this PR is already pretty large)
* Updated Ethermint app to set `TxDecoder`
* Update ante handlers (based on the assumption the tx will be decoded accordingly)
* TX updates -- signature and signing stuff mostly

2018-08-08 19:36 UTC, alexanderbez approved these changes

2018-08-08 20:36 UTC, AdityaSripal commented
@alexanderbez , EmbeddedSignDoc needs to include Fee. Apart from that looks great

2018-08-09 01:08 UTC, merged