Start RPC API implementation
cosmos/ethermint-archive pull request #460
Opened 2018-08-09 10:37 UTC by mslipper

2018-08-09 23:49 UTC, jackzampolin reviewed
I have a couple of initial comments, but this looks like a great start. I think @alexanderbez might have some other comments here.

2018-08-09 23:49 UTC, jackzampolin commented on cmd/ethermintd/root.go
> +	Use:   "ethermintd",
I think we are going to rename the binary to `emintd` and `emintcli`

2018-08-09 23:49 UTC, jackzampolin commented on cmd/ethermintd/root.go
> +	rootCmd.Flags().BoolVarP(&config.EnableRPC, "rpc", "", false, "Enable the HTTP-RPC server")
Can we enable loading these values from a config file as well?

2018-08-09 23:49 UTC, jackzampolin commented on server/apis.go
> +	"github.com/ethereum/go-ethereum/rpc"
`gofmt`

2018-08-09 23:49 UTC, jackzampolin commented on cmd/ethermintd/root.go
> +func runRoot(cmd *cobra.Command, args []string) {
Like the server! This is quite nice with all the signal handling! 💅

2018-08-09 23:49 UTC, jackzampolin commented on server/start.go
> +	"github.com/ethereum/go-ethereum/rpc"
`gofmt`

2018-08-09 23:49 UTC, jackzampolin commented on server/start_test.go
> +	"testing"
`gofmt`

2018-08-09 23:49 UTC, jackzampolin commented on types/config.go
> +type Config struct {
Add `json` (or preferably `yaml` [I think the `json` ones might work for that too...]) struct tags here so we can read the config in from a file.

2018-08-09 23:49 UTC, jackzampolin commented on types/config.go
> +type Config struct {
`~/.emintd.yaml` maybe?

2018-08-09 23:49 UTC, jackzampolin commented on version/version.go
> +func ClientVersion() string {
Going to need to make sure this gets hooked up in the Makefile!

2018-08-09 23:49 UTC, jackzampolin commented on version/version.go
> +func ClientVersion() string {
We can keep that out of scope for this PR, and open an issue.

2018-08-10 05:12 UTC, mslipper commented on cmd/ethermintd/root.go
> +	rootCmd.Flags().BoolVarP(&config.EnableRPC, "rpc", "", false, "Enable the HTTP-RPC server")
Yes, super easy to do with Viper and Cobra together - recommend doing that separately though so we can discuss what we want to name the config file, which filetypes to support, etc.

2018-08-10 05:16 UTC, mslipper commented on cmd/ethermintd/root.go
> +	rootCmd.Flags().BoolVarP(&config.EnableRPC, "rpc", "", false, "Enable the HTTP-RPC server")
Specifically, we can pull config from a variety of sources via Viper - CLI, environment variables, and config files of TOML/YAML/JSON/properties formats.

2018-08-10 05:17 UTC, mslipper commented on types/config.go
> +type Config struct {
See above comment re: Viper. Happy to do implement this now as well, just let me know.

2018-08-10 14:13 UTC, alexanderbez requested changes
Thanks for the contribution @mslipper! Great work. I left a few remarks -- ultimately around structure and what I believe this PR should ultimately introduce. Lmk your thoughts.

2018-08-10 14:13 UTC, alexanderbez commented on cmd/emintd/root.go
> +package main
To be honest, I think we should avoid implementing any logic here until #436 is implemented as that will lay the groundwork for actually starting a TM backend, creating the app and starting things. Most of that will live in `server/` anyway.

Let's leave this file untouched for now (but feel free to keep it in your branch for testing purposes).

2018-08-10 14:13 UTC, alexanderbez commented on server/apis.go
> +package server
Missing proper godocs for all exported functions and fields 👍

2018-08-10 14:13 UTC, alexanderbez commented on server/apis_test.go
> +type APIsTestSuite struct {
I don't think `APIsTestSuite` needs to be public here, right?

2018-08-10 14:13 UTC, alexanderbez commented on server/start.go
>  package server
Can we rename this to `rpc.go`? `start.go` will be for the actual app 👍

2018-08-10 14:13 UTC, alexanderbez commented on server/start.go
> +func StartHTTPEndpoint(ctx context.Context, config *types.Config, apis []rpc.API) (*rpc.Server, error) {
Missing godoc

2018-08-10 14:13 UTC, alexanderbez commented on server/start_test.go
> +package server
`rpc_test.go`

2018-08-10 14:13 UTC, alexanderbez commented on server/start_test.go
> +type TestService struct{}
This doesn't need to be public does it?

2018-08-10 14:13 UTC, alexanderbez commented on server/start_test.go
> +func TestStartHTTPEndpoint_StartStop(t *testing.T) {
Avoid `_` 👍

2018-08-10 14:13 UTC, alexanderbez commented on version/version.go
> +func ClientVersion() string {
Mhmmm, doesn't seem `ClientVersion` introduced any new build-based variables -- I think this is fine unless I'm missing something?

2018-08-10 14:13 UTC, alexanderbez commented on version/version.go
> +func ClientVersion() string {
On another note, maybe move `Ethermint` to a constant and and use `version.AppName` in `NewEthermintApp` as that also uses the same thing.

2018-08-10 14:13 UTC, alexanderbez commented on types/config.go
> +type Config struct {
So Tendermint config will live under `<home>/config/config.toml`. Such a config for the app will live there too (e.g. `<home>/config/emint.toml`). I want to limit confusion for users as much as possible.

I think we need to define a convention for what our config will take, what it'll be named, and how/when it'll be used. For now though, we should move this file to `server/`.

2018-08-13 18:41 UTC, jackzampolin commented on types/config.go
> +type Config struct {
Sounds like this is the convention? Maybe we hold off on implementation here for another PR?

2018-08-13 19:33 UTC, alexanderbez commented on types/config.go
> +type Config struct {
++

2018-08-15 03:43 UTC, mslipper commented on server/start_test.go
> +type TestService struct{}
It does - the HTTP handler does reflection-based checks that the RPC struct is exported.

2018-08-15 19:40 UTC, alexanderbez requested changes
@mslipper thanks for the updates! I'm starting to think RPC and related logic should live under `server/rpc` + also see other comments.

2018-08-15 19:40 UTC, alexanderbez commented on server/apis.go
> +package server
Sorry @mslipper don't wanna be nit-picky here, but can we follow Golang convention here (`<Name> description ...`).

2018-08-15 19:40 UTC, alexanderbez commented on server/apis.go
> +func GetAPIs() []rpc.API {
Should this be `GetRPCAPIs`?

2018-08-15 19:40 UTC, alexanderbez commented on server/apis_test.go
> +func (s *apisTestSuite) TestPublicWeb3API_ClientVersion() {
Should be no `_` in function/method names 👍

2018-08-15 19:40 UTC, alexanderbez commented on server/apis_test.go
> +func (s *apisTestSuite) TestPublicWeb3API_Sha3() {
ditto

2018-08-15 19:40 UTC, alexanderbez commented on server/config.go
> +
ditto regarding godocs 👍

2018-08-15 19:40 UTC, alexanderbez commented on server/rpc.go
> +func StartHTTPEndpoint(ctx context.Context, config *Config, apis []rpc.API) (*rpc.Server, error) {
ditto regarding godocs 👍

2018-08-16 00:44 UTC, alexanderbez commented
@mslipper awesome -- looks like you addressed most of the feedback! I think there is still the notion of moving the rpc (and related logic) implementation to `server/rpc`...at least for now. We're going to have Tendermint RPC, and lite client REST logic there too I imagine.

2018-08-20 20:15 UTC, alexanderbez commented
@mslipper once CI failure is addressed, I'll be happy to approve and merge 👍

2018-08-20 20:18 UTC, jackzampolin commented
Looks like a linting issue.

2018-08-21 15:38 UTC, alexanderbez approved these changes
ACK -- thank you 👍

2018-08-21 15:38 UTC, merged