Aditya/ante test
cosmos/ethermint-archive pull request #470
Opened 2018-08-16 22:39 UTC by AdityaSripal

Wrote tests for ante handler: #463 

Simplified signature verification

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated all relevant documentation (`docs/`)
- [ ] Updated all relevant code comments
- [ ] Wrote tests
- [ ] Added entries in `PENDING.md` that include links to the relevant issue or PR that most accurately describes the change.
___________________________________
For Admin Use:
- [ ] Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- [ ] Reviewers Assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2018-08-23 19:13 UTC, alexanderbez requested changes
@AdityaSripal thanks for the updates -- looking great! I've left some feedback I think that should be addressed.

Let me know if you're able to accommodate these changes soon? If not, I'll be happy to wrap them up and finish any additional functionality/testing.

2018-08-23 19:13 UTC, alexanderbez commented on Gopkg.lock
> -  digest = "1:fcdf62d2d7e43c2565d6f8707ab4eae54dac702ed4bafb194b85139f0508929f"
I'm not sure if we're supposed to be getting this diff -- try updating your dev tools?

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> +	sdkCtx.GasMeter().ConsumeGas(verifySigCost, "ante verify")
Seems this was copy-pasta, let's update the description to be a bit more descriptive, like `Ethereum signature verification cost`.

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> +	// validate AccountNonce (called Sequence in AccountMapper)
`// validate the account nonce (referred to as sequence in the AccountMapper)`

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> +	acc := am.GetAccount(sdkCtx, addr[:])
I think we can just do `addr.Bytes()`, no?

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> +		return sdkCtx, sdk.ErrInvalidSequence(fmt.Sprintf("Wrong AccountNonce: expected %d", seq)).Result(), true
`invalid account nonce`

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> +	err = acc.SetSequence(seq + 1)
Let's add a newline break here. Also, do we really want to panic or can we return an error? What signals for panic and what signals for returning an error? We should add that to the godoc of this function I think.

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> +			return sdkCtx, err.Result(), true
Good catch 👏

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante.go
> -		if err.Code() != sdk.CodeOK {
Why remove the explicit check here? Won't `err` never be nil because of the named return in `validateSignature`?

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante_test.go
> +// Test EthTx Antehandler
I think we can remove the comment stubs and update each test function with the appropriate prefix: `TestEthTx...` and `TestEmbeddedTx...`.

2018-08-23 19:13 UTC, alexanderbez commented on handlers/ante_test.go
> +
Let's remove unnecessary new lines

2018-08-23 19:13 UTC, alexanderbez commented on handlers/test_common.go
> +func SetupMultiStore() (sdk.MultiStore, *sdk.KVStoreKey) {
Does this need to be exported? `createTestMultiStore` should suffice I think.

2018-08-23 19:13 UTC, alexanderbez commented on types/test_common.go
> +	// Register any desired SDK msgs to be embedded
I think this comment is redundant

2018-08-23 19:13 UTC, alexanderbez commented on types/test_common.go
> +func NewStdFee() auth.StdFee {
`NewTestStdFee`

2018-08-23 19:13 UTC, alexanderbez commented on types/test_common.go
> +package types
I think we need to add `nolint` to all of these?

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +func (tx Transaction) VerifySig(chainID *big.Int) (ethcmn.Address, error) {
Missing godoc.

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +	// the signer used to derive it.
I think it might also help to add to the documentation why we need this?

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +		// If the signer used to derive from in a previous
This comment is a bit confusing...or least does not seem to line up with what the logic does? Seems we're loading cache and if the signer is the same as the one we derived from the tx, we return the cached from address?

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +	// Do not allow unprotected chainID
unless it's a sentence, let's not capitalize

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +		return ethcmn.Address{}, errors.New("Cannot have 0 as ChainID")
`invalid chainID: unprotected` or `invalid chainID: 0` ? Also, should we have this check before we create the signer and check the cache?

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +	signBytes := rlpHash([]interface{}{
This is also used in `Transaction#Sign`. Seems it warrants creating a utility function? (e.g. `TransactionSigBytes`)

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +		// If the signer used to derive from in a previous
I realized this was copied from Geth, but their comments do not always make sense ^__^

2018-08-23 19:13 UTC, alexanderbez commented on types/tx.go
> +// Copies Ethereum tx's Protected function
I think we can remove this comment?

2018-08-23 19:13 UTC, alexanderbez commented on types/wire.go
> +	auth.RegisterWire(codec)
I think this should happen in `CreateCodec` in `app/ethermint.go`.

2018-08-24 16:46 UTC, alexanderbez commented
@AdityaSripal please also rebase the latest `master` as `EmbeddedTx` is now removed 🙌

2018-08-31 20:46 UTC, alexanderbez approved these changes

2018-08-31 20:47 UTC, alexanderbez commented
@AdityaSripal I've updated and resolved the conflicts from merging the latest `master`. I've also made a few updates.

Is there anything else that needs to be done? I think this is ready for merge.

2018-08-31 20:52 UTC, jackzampolin commented
Just looking through the tests here. Is there any other functionality (account/transaction generation) that we can abstract into `handlers/test_common.go`, or is that premature optimization?

2018-08-31 21:11 UTC, AdityaSripal commented
@alexanderbez no i had all the tests i wanted on there. Thanks for wrapping this up! Was only going to get a chance to look at this after Vesting

2018-09-01 01:41 UTC, alexanderbez commented
@jackzampolin that'd probably would live in `types/test_common.go` but I don't see any atm.

2018-09-01 01:42 UTC, merged