Implement Initial Spec/Documentation
cosmos/ethermint-archive pull request #471
Opened 2018-08-20 12:33 UTC by alexanderbez

Implemented some initial documentation. Please feel free to modify!

closes #468 

----

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated all relevant documentation (`docs/`)
- [ ] Updated all relevant code comments
- [ ] Wrote tests
- [ ] Added entries in `PENDING.md` that include links to the relevant issue or PR that most accurately describes the change.
___________________________________
For Admin Use:
- [ ] Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- [ ] Reviewers Assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2018-08-20 12:35 UTC, alexanderbez commented
@AdityaSripal please review the information documented in the `Transaction` spec. Could you maybe add some notes on fees/gas and also double check my signature spec?

2018-08-21 15:49 UTC, AdityaSripal commented on docs/spec/transactions/README.md
> +Ethermint supports [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)
Should we have a section explaining how to fork from Ethereum genesis, since we only support EIP-155

2018-08-21 15:53 UTC, AdityaSripal requested changes

2018-08-21 15:53 UTC, AdityaSripal commented on docs/spec/transactions/README.md
> +`EmbeddedTx` contains a canonical signature structure that itself contains the
> A client is expected to sign the `Transaction` just as in Ethereum

Not true with EmbeddedTx anymore

2018-08-21 15:53 UTC, AdityaSripal commented on docs/spec/transactions/README.md
> +This prevents "replay attacks", where the same message could be executed over and
May want to mention chainID as a way to prevent cross-chain replay attacks

2018-08-21 15:53 UTC, AdityaSripal commented on docs/spec/transactions/README.md
> +the signer of the embedding `Transaction`. As such, there will be one duplicate
Not true anymore

2018-08-21 15:53 UTC, AdityaSripal commented
With current Antehandler structure, an `EmbeddedTx` can have empty `Transaction` signature and still pass

2018-08-21 18:14 UTC, jackzampolin commented on docs/spec/transactions/README.md
> +Ethermint supports [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)
I think the plan here is to export state at a particular block and have a utility for importing that state.

2018-08-21 18:29 UTC, alexanderbez commented on docs/spec/transactions/README.md
> +Ethermint supports [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)
Yeah, that should be in an entire separate document not under `spec/` 👍 -- feel free to add it.

2018-08-21 22:21 UTC, jackzampolin commented on docs/spec/transactions/README.md
> +This prevents "replay attacks", where the same message could be executed over and
Don't know if we need to do this.

2018-08-21 22:21 UTC, jackzampolin commented on docs/spec/transactions/README.md
> +`EmbeddedTx` contains a canonical signature structure that itself contains the
So what should we update here?

2018-08-21 22:22 UTC, jackzampolin commented on docs/spec/transactions/README.md
> +Ethermint supports [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)
I've updated the README "Roadmap" section to reflect this, we don't have `spec` for this yet.

2018-08-21 22:43 UTC, jackzampolin commented on docs/spec/transactions/README.md
> +the signer of the embedding `Transaction`. As such, there will be one duplicate
Can you push a change here to fix that?

2018-08-22 00:13 UTC, AdityaSripal commented on docs/spec/transactions/README.md
> +`EmbeddedTx` contains a canonical signature structure that itself contains the
> However, just as in Cosmos, Ethermint will support multiple signers.

This sounds as though we want outer Transactions to support multiple signers. May be useful to specify this is true for embedded tx's only

2018-08-22 18:06 UTC, alexanderbez commented
@jackzampolin @AdityaSripal I've addressed the PR reviews 👍

2018-08-22 18:15 UTC, AdityaSripal approved these changes

2018-08-22 19:58 UTC, jackzampolin commented
Merging

2018-08-22 19:58 UTC, merged