Stub out other RPC endpoints
cosmos/ethermint-archive pull request #472
Opened 2018-08-21 22:34 UTC by mslipper

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated all relevant documentation (`docs/`)
- [ ] Updated all relevant code comments
- [ ] Wrote tests
- [ ] Added entries in `PENDING.md` that include links to the relevant issue or PR that most accurately describes the change.
___________________________________
For Admin Use:
- [ ] Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- [ ] Reviewers Assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2018-08-21 22:55 UTC, jackzampolin reviewed
This looks good to me! Maybe we need to add some documentation here (`/docs/web3`) that notes methods with fixed returns (mining, uncles, etc...) and links to the web3 spec we are implementing.

2018-08-23 16:05 UTC, alexanderbez requested changes
Thanks for the contrib @mslipper -- I left some feedback 👍

2018-08-23 16:05 UTC, alexanderbez commented on Gopkg.lock
> -  digest = "1:fcdf62d2d7e43c2565d6f8707ab4eae54dac702ed4bafb194b85139f0508929f"
I don't think we should be getting this diff. Can you update your dev tools?

2018-08-23 16:05 UTC, alexanderbez commented on server/rpc/eth_api.go
> +func NewPublicEthPI() *PublicEthAPI {
`NewPublicEthAPI`*

2018-08-23 16:05 UTC, alexanderbez commented on server/rpc/eth_api.go
> +// PublicEthAPI is the web3_ prefixed set of APIs in the Web3 JSON-RPC spec.
This is the same description as `PublicWeb3API` -- what's the difference?

2018-08-23 16:05 UTC, alexanderbez commented on server/rpc/eth_api.go
> +func (e *PublicEthAPI) Coinbase() common.Address {
You can just use a named return variable here and simply `return`

2018-08-25 22:24 UTC, mslipper commented on server/rpc/eth_api.go
> +// PublicEthAPI is the web3_ prefixed set of APIs in the Web3 JSON-RPC spec.
I meant to make it the eth_ prefixed APIs. Fixing.

2018-08-25 22:33 UTC, mslipper commented on Gopkg.lock
> -  digest = "1:fcdf62d2d7e43c2565d6f8707ab4eae54dac702ed4bafb194b85139f0508929f"
Tools updated.

2018-08-28 13:15 UTC, alexanderbez commented
Awesome! Thanks @mslipper. Going forward, if there are other issues you can think of in regards to Ethereum RPC/API related work, lets create issues for them and triage them 👍

2018-08-28 13:15 UTC, alexanderbez approved these changes

2018-08-28 13:15 UTC, merged