WIP: Reintroduce Embedded Transactions
cosmos/ethermint-archive pull request #478
Opened 2018-08-30 21:39 UTC by alexanderbez

- Reintroduce the notion of a dedicated Cosmos SDK address
- Add support for RLP encoding/decoding
- Updated signature verification logic (based off #470)
- Updated ante handler
- Updated docs

closes: #477 

----

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Updated all relevant documentation (`docs/`)
- [ ] Updated all relevant code comments
- [ ] Wrote tests
- [ ] Added entries in `PENDING.md` that include links to the relevant issue or PR that most accurately describes the change.
___________________________________
For Admin Use:
- [ ] Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- [ ] Reviewers Assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2018-08-30 21:40 UTC, alexanderbez commented
I just need to update the spec doc and this should be g2g.

2018-08-30 22:06 UTC, AdityaSripal requested changes

2018-08-30 22:06 UTC, AdityaSripal commented on app/ethermint.go
> +	logger tmlog.Logger, db dbm.DB, ethChainCfg *ethparams.ChainConfig,
Don't need `ethChainCfg` anymore

2018-08-30 22:48 UTC, jackzampolin approved these changes

2018-08-31 00:07 UTC, AdityaSripal approved these changes

2018-08-31 12:34 UTC, alexanderbez commented on app/ethermint.go
> +	logger tmlog.Logger, db dbm.DB, ethChainCfg *ethparams.ChainConfig,
Will remove. I don't even know yet how we'll tie these things together. Maybe we'll need an EVM module that we pass this stuff to.

2018-08-31 12:38 UTC, merged