WIP: TX Routing Refactor
cosmos/ethermint-archive pull request #496
Opened 2018-10-26 20:43 UTC by alexanderbez

Redesign the way Ethereum transactions are handled by treating them as first class citizen types along with any potential future SDK messages types by using the Amino encoding protocol. Web3 compatibility is still maintained as Ethereum transactions will still be RLP encoded over the wire but to Tendermint, they'll be re-encoded via Amino.

closes: #492

----

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ethermint/blob/master/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added entries in `PENDING.md` with issue # 
- [ ] rereviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge pull request #XYZ: [title]"

2018-11-09 21:35 UTC, alexanderbez commented
I believe most of the routing logic is done. Just need to update (re-implement) the ante handler unit tests.

2018-11-21 20:29 UTC, AdityaSripal commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
Shouldn't this function take an `sdk.Tx` argument?

2018-11-21 20:29 UTC, AdityaSripal commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
This looks like the EthereumTx is getting embedded as a message in an auth.StdTx.

I thought the idea was to have application accept an EthereumTx (which implemented both sdk.Msg and sdk.Tx interfaces) and also accept auth.StdTx, which could contain governance, staking, and other SDK messages.

2018-11-23 03:16 UTC, alexanderbez commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
So the implementation has changed a bunch of times now, so apologies if it gets confusing.

Yes, you are correct, it is now simply a message inside a `auth.StdTx`. I don't really see any immediate compelling reason to also make it it's own tx type. We can still use staking, governance, etc. messages. The EVM is now just another module that has it's own message(s)...the Ethereum message.

Can you list some advantages or reasons why it should be its own tx type?

2018-11-26 15:16 UTC, cwgoes commented
I'd like to review this but it's a bit lower priority than GoS. If you can wait a day or two @alexanderbez I'll get to it ;) .

2018-11-26 15:53 UTC, alexanderbez commented
No rush @cwgoes -- take your time.

2018-11-26 21:03 UTC, jackzampolin commented on app/ante.go
> +		// TODO: Handle gas/fee checking and spam prevention. We may need two
What is the current thought here? Is there any way to avoid the SDK gas?

2018-11-26 21:07 UTC, jackzampolin commented on docs/spec/transactions/README.md
> +`sdk.Msg` contained in an `auth.StdTx`. All relevant Ethereum transaction information
Links to godocs here would significantly help reader comprehension here I think, but optional.

2018-11-26 21:11 UTC, jackzampolin commented on x/evm/types/msg.go
> +var _ sdk.Msg = MsgEthereumTx{}
What is this used for?

2018-11-26 21:14 UTC, jackzampolin commented on x/evm/types/msg.go
> +// GetSigners returns the expecter signers for an Ethereum transaction message.
```suggestion
// GetSigners returns the expected signers for an Ethereum transaction message.
```

2018-11-27 06:25 UTC, zmanian approved these changes

2018-11-27 08:14 UTC, AdityaSripal commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
No big disadvantage except having wasted fields in the stdtx.

Having EVM be just another module makes sense

2018-11-27 08:17 UTC, AdityaSripal commented on x/evm/types/msg.go
> +var _ sdk.Msg = MsgEthereumTx{}
just verifies MsgEthereumTx implements sdk.Msg

2018-11-27 08:29 UTC, AdityaSripal commented on app/ante.go
> +func ethAnteHandler(
Maybe this isn't a part of this PR. But i believe we need eth tx to fail on checkTx for invalid sigs and insufficient fees here to prevent DOS vector.

Need to check sigs and collect fees here, then EVM can be passed `core/types/Message` to prevent redoing work.

https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L386

2018-11-27 08:32 UTC, AdityaSripal commented on app/ante.go
> +	ctx sdk.Context, ethTx *evmtypes.MsgEthereumTx, ak auth.AccountKeeper,
Also docs here should clarify that ethTx is an `sdk.Msg`

2018-11-27 13:07 UTC, alexanderbez commented on app/ante.go
> +		// TODO: Handle gas/fee checking and spam prevention. We may need two
Ehhhh, so we need to come up with a gas/fee market model. The EVM has it's own gas consumption via OPCODES and the SDK has it's own gas consumption via the gas meter.

The TODO here is for SDK transactions, but it's something we should discuss.

2018-11-27 13:16 UTC, alexanderbez commented on docs/spec/transactions/README.md
> +`sdk.Msg` contained in an `auth.StdTx`. All relevant Ethereum transaction information
Agreed. Done!

2018-11-27 13:20 UTC, alexanderbez commented on app/ante.go
> +	ctx sdk.Context, ethTx *evmtypes.MsgEthereumTx, ak auth.AccountKeeper,
Updated 👍

2018-11-27 13:27 UTC, alexanderbez commented on app/ante.go
> +func ethAnteHandler(
Yes, good point. Ethereum handles this at their mempool level iirc. You're right in that we simply cannot skip at this is a DoS vector.

I think we should validate the signature and check if the account has enough funds to cover gas costs. Anything else?

> Need to check sigs and collect fees here, then EVM can be passed core/types/Message to prevent redoing work.

Can you elaborate @AdityaSripal? Looking at [`ApplyTransaction`](https://github.com/ethereum/go-ethereum/blob/v1.8.16/core/state_processor.go#L88), what would be modified? Would the ante handler check if we're in `checkTx` mode and run verification, otherwise just pass it along to the EVM?

In either case, a separate PR.

2018-11-27 13:32 UTC, alexanderbez commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
Actually, it might be worth saving space on fields. Thoughts?

2018-11-27 20:52 UTC, AdityaSripal commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
It's going to be a tradeoff between storage savings and semantic niceness.

Either way we're going to have to break sdk semantics:

1) If we make `EthereumTx` be a transaction, it will have to implement both `sdk.Msg` and `sdk.Tx` as we did before.

2) If `EthereumTx` an `sdk.Msg`, it will encapsulate authentication data which should be in transaction.

I think for the reasons above, 2 is probably a cleaner solution sematics-wise.

I'm not too familiar with Ethermint's storage performance/requirements, but considering the vast majority of transactions sent to Ethermint will probably be `EthereumTx` transactions, the extra space wasted on each one could be untenable.

 Easier to reason about this tradeoff if we know the relative priorities of semantics/storage-optimization and if Ethermint is already having storage issues or if those are being fixed by BoltBD and turboGeth (i haven't been following progress on that closely)

2018-11-27 21:49 UTC, alexanderbez commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
Valid points and for reasons you stated in (2) I'm going to leave as is. It will not be difficult to change later down the road if we find this to be problematic. Keep in mind most of these fields will simply have their zero-values.

2018-11-27 21:56 UTC, AdityaSripal approved these changes

2018-11-27 22:01 UTC, jackzampolin approved these changes
Looks good! I think we are waiting on @cwgoes for a final look.

2018-11-28 16:47 UTC, cwgoes requested changes
A few questions about the ante handler.

2018-11-28 16:47 UTC, cwgoes commented on app/ante.go
> +		// TODO: Handle gas/fee checking and spam prevention. We may need two
I think we need to use the same gas mechanism (somehow). In particular, we want transactions which will both run EVM code and SDK module code (via precompile hooks), and the user should only need to set one total gas allocation.

2018-11-28 16:47 UTC, cwgoes commented on app/ante.go
> +func defaultAnteHandler(
Can we find a way to import all this code (which looks like it was more or less copied from the SDK) instead of duplicating it? If that requires the SDK `x/ante` module to export more things, that's fine - this seems like a common necessity (modify the ante handler) which will be useful beyond Ethermint.

2018-11-28 16:47 UTC, cwgoes commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
Is there a particular reason we require only one `Msg` in Ethereum transactions? A user might want to send a multi-`Msg` transaction where one or more of the `Msg`s is/are a `MsgEthereumTx` but other(s) are not.

2018-11-28 16:47 UTC, cwgoes commented on app/ante.go
> +		// NOTE: We could use the SDK's ante handler, but differences may exist in
Ah I commented on this later. Even if we don't use the full SDK ante-handler, can we reuse shared subcomponents?

Alternatively, maybe we should parameterize the SDK ante handler over gas price configurations.

2018-11-28 16:47 UTC, cwgoes commented on app/ante.go
> +		if ethTx, ok := isEthereumTx(stdTx); ethTx != nil && ok {
Hmm, shouldn't we still call `ValidateBasic` (e.g. check memo size and anything else on `StdTx` not in the `MsgEthereumTx`)?

2018-11-28 18:50 UTC, jackzampolin commented on app/ante.go
> +func defaultAnteHandler(
Really like this idea!

2018-11-28 19:17 UTC, alexanderbez commented on app/ante.go
> +		// TODO: Handle gas/fee checking and spam prevention. We may need two
You mean use Ethereum's gas consumption model?

2018-11-28 19:50 UTC, alexanderbez commented on app/ante.go
> +func defaultAnteHandler(
The initial motivation was if we need different or custom business logic, but it makes sense to rather adapt the SDK's ante handler to be more flexible. So I'm now using the SDK's ante handler.

2018-11-28 19:50 UTC, alexanderbez commented on app/ante.go
> +		// NOTE: We could use the SDK's ante handler, but differences may exist in
Agreed. Using the SDK's ante handler right now. If we need to change anything, it should be allowed by the upstream ante handler.

2018-11-28 19:53 UTC, alexanderbez commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
Perhaps, but that is a bit tricker to reason about. I think semantically it makes it easier to reason about if it's just a single ethereum tx or one or more SDK txs.

e.g. If I have an eth tx and a bunch of SDK txs, the fee/sigs on the auth.Stdx will only cover the SDK tx and the eth tx will have it's own...it just seems messy.

Is this something we need to think about more?

2018-11-28 19:56 UTC, alexanderbez commented on app/ante.go
> +		if ethTx, ok := isEthereumTx(stdTx); ethTx != nil && ok {
It's presumed those fields will be empty. Granted since we agreed on doing basic checks for ethereum tx msg during CheckTx, I can add this (separate PR).

2018-11-28 19:56 UTC, alexanderbez commented
@cwgoes I believe I addressed most of your comments 👍

2018-11-28 21:27 UTC, cwgoes commented on app/ante.go
> +func isEthereumTx(tx auth.StdTx) (*evmtypes.MsgEthereumTx, bool) {
I see, I see - this is probably fine for now, although see https://github.com/cosmos/ethermint/pull/496#discussion_r237162329 which I think we do need to think about.

2018-11-28 21:28 UTC, cwgoes commented on app/ante.go
> +		if ethTx, ok := isEthereumTx(stdTx); ethTx != nil && ok {
Presumed, perhaps, but I as a malicious user shall violate your presumptions!

Separate PR is fine.

2018-11-28 21:48 UTC, cwgoes approved these changes

2018-11-28 22:19 UTC, merged