WIP: CheckTx AnteHandler for Ethereum Tx Messages
cosmos/ethermint-archive pull request #505
Opened 2018-11-29 18:46 UTC by alexanderbez

closes: #504 

----

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ethermint/blob/master/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added entries in `PENDING.md` with issue # 
- [ ] rereviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge pull request #XYZ: [title]"

2018-12-12 13:54 UTC, cwgoes requested changes
Structure looks reasonable to me, several comments / requests for clarification.

2018-12-12 13:54 UTC, cwgoes commented on Gopkg.toml
> +  # version = "v0.27.0"
We've now released `0.28.0`

2018-12-12 13:54 UTC, cwgoes commented on Gopkg.toml
> +  revision = "v0.27.0-dev1"
I believe Tendermint has a newer release as well

2018-12-12 13:54 UTC, cwgoes commented on app/ante.go
> +			return auth.NewAnteHandler(ak, fck)(ctx, castTx, sim)
Can we avoid calling `NewAnteHandler` each time? Not a huge deal, but would be cleaner.

2018-12-12 13:54 UTC, cwgoes commented on app/ante.go
> +	chainID, ok := new(big.Int).SetString(ctx.ChainID(), 10)
A bit confused - what's `10`? Is this the network ID we're using for Ethermint or something?

Seems like it should be a constant / parameter somewhere.

2018-12-12 13:54 UTC, cwgoes commented on app/ante.go
> +	// validate sender/signature
I would do this last, since it's most expensive

2018-12-12 13:54 UTC, cwgoes commented on app/ante.go
> +// cover intrinsic gas.
What exactly is "intrinsic gas" - is that the 21,000 gas minimum for any `CALL` operation (IIRC)?

Can we link to the spec or a doc somewhere?

2018-12-12 13:54 UTC, cwgoes commented on app/ante.go
> +	if ethTxMsg.Data.AccountNonce < seq {
Is this how Ethereum behaves (any increasing nonce OK)?

I wonder if we want to require exactly monotonically increasing, or at least a bound...

2018-12-12 13:54 UTC, cwgoes commented on app/ante.go
> +	fee := sdk.Coins{sdk.NewInt64Coin(types.DenomDefault, feeAmt.Int64())}
If the transaction can only pay a fee in `DenomDefault`, we should just check one denom and assert that `ctx.MinimumFees()` has no other denoms (elsewhere), I think

2018-12-12 13:54 UTC, cwgoes commented on crypto/secp256k1.go
> +package crypto
Should this go upstream (in Tendermint, perhaps)?

2018-12-12 13:54 UTC, cwgoes commented on x/evm/types/msg.go
> +	copy(addr[:], ethcrypto.Keccak256(pub[1:])[12:])
Is this how Ethereum addresses are calculated (looks like the first `12` bytes are ignored - padding?)

Can we link to a spec here?

2018-12-14 22:28 UTC, alexanderbez commented on app/ante.go
> +	// validate sender/signature
Updated.

2018-12-14 22:30 UTC, alexanderbez commented on app/ante.go
> +	chainID, ok := new(big.Int).SetString(ctx.ChainID(), 10)
It's the base when attempting to set a big int from a string (base 10). I added a comment to make that more clear.

2018-12-14 22:35 UTC, alexanderbez commented on app/ante.go
> +// cover intrinsic gas.
Correct. I updated the godoc:

```golang
// Intrinsic gas for a transaction is the amount of gas
// that the transaction uses before the transaction is executed. The gas is a
// constant value of 21000 plus any cost inccured by additional bytes of data
// supplied with the transaction.
```

2018-12-17 15:45 UTC, alexanderbez commented on app/ante.go
> +	if ethTxMsg.Data.AccountNonce < seq {
Yes, see [here](https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L592-L595).

No reason we can't be consistent and require monotonically increasing nonces.

2018-12-17 15:56 UTC, alexanderbez commented on app/ante.go
> +	fee := sdk.Coins{sdk.NewInt64Coin(types.DenomDefault, feeAmt.Int64())}
Sure! Are you suggesting that we simply assert that `ctx.MinimumFees()` only contains `DenomDefault`?

2018-12-17 16:00 UTC, alexanderbez commented on crypto/secp256k1.go
> +package crypto
TM already has a `secp256k1` package, but unfortunately it is not compatible (ethereum uses Keccak) :-(

Hence I had to implement a wrapper.

2018-12-17 16:06 UTC, alexanderbez commented on x/evm/types/msg.go
> +	copy(addr[:], ethcrypto.Keccak256(pub[1:])[12:])
Yes. Added a reference to the yellow paper section.

2018-12-17 16:20 UTC, alexanderbez commented on Gopkg.toml
> +  revision = "v0.27.0-dev1"
Updated to `v0.27.0` as that is what `v0.28.0` of the SDK uses 👍

2018-12-17 18:31 UTC, alexanderbez commented on app/ante.go
> +			return auth.NewAnteHandler(ak, fck)(ctx, castTx, sim)
No longer necessary as I'm not using the SDK's ante handler (for now).

2018-12-17 18:31 UTC, alexanderbez commented on Gopkg.toml
> +  # version = "v0.27.0"
Im using a specific revision until https://github.com/cosmos/cosmos-sdk/pull/3135 is merged 👍

2018-12-17 18:43 UTC, alexanderbez commented
@cwgoes updated 👍

2018-12-17 21:53 UTC, cwgoes commented on app/ante.go
> +	fee := sdk.Coins{sdk.NewInt64Coin(types.DenomDefault, feeAmt.Int64())}
Yes.

2018-12-17 21:53 UTC, cwgoes commented on crypto/secp256k1.go
> +package crypto
Ah darn, OK then.

2018-12-17 21:54 UTC, cwgoes commented on app/ante.go
> +	if ethTxMsg.Data.AccountNonce < seq {
Do you know why Ethereum chose to do this? I recall that we discussed it and explicitly rejected it because it provided less user certainty and could lead to faster nonce overflow.

2018-12-17 21:54 UTC, cwgoes commented on app/ante.go
> +	chainID, ok := new(big.Int).SetString(ctx.ChainID(), 10)
Ah, haha - thanks.

2018-12-18 14:10 UTC, alexanderbez commented on app/ante.go
> +	fee := sdk.Coins{sdk.NewInt64Coin(types.DenomDefault, feeAmt.Int64())}
Created an issue: https://github.com/cosmos/ethermint/issues/507
and added a comment.

2018-12-18 14:16 UTC, alexanderbez commented on app/ante.go
> +	if ethTxMsg.Data.AccountNonce < seq {
Checked the yellow paper and it states: `the transaction nonce is valid (equivalent to the
sender account’s current nonce);`. So not sure why Geth does this? In any case, I updated the ante handler check.

2018-12-18 14:16 UTC, alexanderbez commented
@cwgoes addressed your comments.

2018-12-18 16:02 UTC, cwgoes approved these changes

2018-12-18 16:10 UTC, merged