Implement BlockKeeper for RPC-compatible block storage
cosmos/ethermint-archive pull request #506
Opened 2018-12-03 22:04 UTC by mslipper

2018-12-07 01:11 UTC, jackzampolin reviewed
This looks 👌

2018-12-07 01:11 UTC, jackzampolin commented on x/evm/types/block_keeper.go
> +// TODO @mslipper: Transaction receipts need to be included separately.
Does this need another keeper cc @alexanderbez

2018-12-07 14:02 UTC, alexanderbez requested changes
> 1. I'm not 100% clear on the various backing store implementations - i.e., `CacheMultiStore`, `CommitMultiStore`, etc. @alexanderbez would love to pick your brain on what each one does so that I can use the appropriate one here.

Yes, certainly. We can discuss more. I don't think we'll be using the context's multi-store directly here though. We need to keep a separate store from the commit multi-store.

> 2. I'm using Geth's `rawdb` package to make short work of persisting blocks in a manner that'll make querying them easy. Under the hood, `rawdb` persists everything in RLP. I know we discussed using Amino for everything under-the-hood, but given that another one of the project's stated goals is to reuse as much code from Geth as possible I thought that the additional code reuse `rawdb` provided was an OK tradeoff.

Is this something we cannot tackle with using our own logic? i.e. look into how rawdb does it. It seems all we need is to be able to get by hash/number. I think we can do this ourselves, no? I'd like to avoid using mixed encoding schemes here if possible. Yes, we need to keep web3 compatibility, but I don't see how the data stored here correlates to that as at the end of the day the user/client is getting the same block (`ethtypes.Block`).

> 3. I see that the EVM/ABCI application is now implemented. @alexanderbez - would also like to discuss the best way to instantiate this Keeper in that context.

I think this keeper should be separate entirely from the EVM module. In fact, neither the ABCI or the EVM module are complete (there is no EVM keeper yet!).

> 4. Transaction receipts will be a bit tricky, and will be handled in a separate PR after this one since they are generated from consensus and not the materialized list of block transactions.

I think we need to discuss receipts more in general. We should walk through how they're generated and when/where they're persisted in Geth first.

> I'd imagine that the `SetBlock` method would be called in the `EndBlocker` ABCI method.

So I cannot recall exactly the discussion conclusion we had on this entire subject (shame, we should keep better notes). Essentially the thinking here is to keep these blocks _separate_ from consensus state...essentially duplicates of what TM already stores? (cc @cwgoes)

---- 

I think this PR is a good reference point/prototype sketch. However, I'd be more thrilled to see a keeper/module spec first answering many of the above. From there we can go ahead and proceed with implementation.

Primarily, in the spec I'd like to see at least the following answered:

1. How will the blocks be persisted?
2. When will the blocks be persisted?
3. How this hooks into web3/RPC?
4. How this relates to receipts?

UPDATE: So after todays call, the consensus seems to be that a bulk, if not all, of the web3/RPC functionality should be served via Tendermint RPC somehow via an indexing system (e.g. tags). This is what I think we actually alluded to in the previous discussion.

2018-12-10 16:19 UTC, cwgoes commented
Do I understand correctly that the intent of this PR (once the higher-level code is updated) is to store every block in a database? I think we should very much try to avoid doing this if possible - this will essentially double the storage, since Tendermint *also* stores blocks.

First, I think we should figure out the requisite *additional* information we need to store to serve web3 queries (on top of what the SDK/Tendermint) will already track. Once we have a list (of fields, query types, indexing efficiency requirements) we should be able to run through the list and figure out how we need to deal with each item, taking the first possible of the following approaches in order of preference:

1. Tag a transaction and query through the Tendermint interface
2. Store minor additional transaction-related data (but not the full tx or the block) in a separate DB to be used for queries
3. Store the entire transaction and/or part of the block in a separate DB to be used for queries

It is absolutely fine if we need to add features to Tendermint in order for (1) to be viable - whatever Ethermint needs is likely to be also required by other future SDK applications.

2018-12-10 17:19 UTC, alexanderbez commented
I think there is majority consensus on this. In addition to consensus on listing out what we really need for web3 and how to achieve it. I believe this should be our next step. Let's walk through this together @mslipper.

2018-12-10 17:19 UTC, closed without merging

2018-12-11 01:21 UTC, mslipper commented
Sounds good. Are we meeting tomorrow?

2018-12-11 04:18 UTC, alexanderbez commented
Yes @mslipper